CRM/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/',include("main.urls",namespace="main")),
]

main/urls.py
from django.urls import path
from main import views
app_name = "main"

urlpatterns = [
    path("userlogin/",views.userlogin,name="userlogin"),
    path("userlogout/",views.userlogout,name="userlogout"),
    path("index/",views.index,name="index"),
    path('newservice/',views.newservice,name="newservice"),
    path('tbclist/',views.tbclist,name='tbclist'),
    path('tbblist/',views.tbblist,name='tbblist'),
    path('pfolist/',views.pfolist,name='pfolist'),
    path('inpfolist/',views.inpfolist,name='inpfolist'),
    path('pfplist/',views.pfplist,name='pfplist'),
    path('tbdlist/',views.tbdlist,name='tbdlist'),
    path('closedloglist/',views.closedloglist,name='closedloglist'),
    path('tbc/<str:sid>/',views.tbc,name='tbc'),
    path('tbb/<str:sid>/',views.tbb,name='tbb'),
    path('engineerinspection/<str:sid>/',views.engineerinspection,name='engineerinspection'),
    path('pendingforpayment/<str:osid>/',views.pendingforpayment,name='pendingforpayment'),
    path('pendingforoutbound/<str:isid>/',views.pendingforoutbound,name='pendingforoutbound'),
    path('inwarrantypendingforoutbound/<str:osid>/',views.inwarrantypendingforoutbound,name='inwarrantypendingforoutbound'),
    path('tbd/<str:logid>/',views.tbd,name='tbd'),
    path('productslist/',views.productlist,name='productlist'),
    path('iproduct/<str:partcode>/',views.getInventoryProduct,name='iproduct'),

    path('inventory/',views.inventory,name="inventory"),

    path('inpspectionlist/',views.inspection_list,name='inspection_list'),

    path('pending-inbound/',views.stockapproval,name="pending_inbound"),
    path('testing/',views.testingapi),

    path('test/',views.testing),

    path('logapi/',views.logapi),
    path('approval/',views.approvalapi),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/navstyle.css' %} ">
    <link rel="stylesheet" href="{% static 'css/utils.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% comment %} <title>navbar</title> {% endcomment %}

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    {% block csslinks %}  {% endblock csslinks %}
    {% block title %}  <title>www.cctvserv.com/product-management</title> {% endblock title %}

</head>
<body>
    <nav class="navbar">
        <div class="nav-left">
            <div class="nav-brand">
                <span>brand and logo.........</span>
            </div>
            <div class="navigation">
                <ul>
                    <li><a href="{% url 'main:index' %}">  Dashboard </a></li>
                    <li>
                        <a href="#"> Service  <span>	&#9662; </span> </a>
                        <ul class="dropdown">
                            <li>
                                <a href=""> Repair <span>&#9656;</span> </a>
                                <ul class="subdropdown">
                                    <li><a href="{% url 'main:newservice' %}"> Apply </a></li>
                                    <li><a href="#"> Inquire </a></li>
                                </ul>
                            </li>
                            <li>
                                <a href=""> Order <span>&#9656;</span></a>
                                <ul class="subdropdown">
                                    <li><a href="#"> Apply </a></li>
                                    <li><a href="#"> Inquire </a></li>
                                </ul>
                            </li>
                            <li>
                                <a href=""> Lorem <span>&#9656;</span></a>
                                <ul class="subdropdown">
                                    <li><a href="#"> Lorem ipsum </a></li>
                                    <li><a href="#"> Lorem ipsum </a></li>
                                    <li><a href="#"> Lorem ipsum </a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="{% url 'main:inventory' %}">  Inventory </a></li>
                    <li><a href="{% url 'main:closedloglist' %}">  Service Logs </a></li>
                </ul>
            </div>
        </div>
        <div class="nav-right">
            <div class="nav-profile">
                <span><a href="{% url 'main:userlogout' %}">Logout</a></span>
            </div>
        </div>
    </nav>


    {% block content %}{% endblock content %}

    {% block detailtabs %}{% endblock detailtabs %}

    {% block jslinks %}{% endblock jslinks %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block csslinks %}

<link rel="stylesheet" href="{% static 'css/allocatestyle.css' %}">
{% endblock csslinks %}

{% block content %}
    <div class="container">

<!-- Allocate starts here  -->
        <h3>Service</h3>
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th>Case</th>
                    <th> Pending Cases</th>
                    <th> Operation</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>TBC</td>
                    <td>1</td>
                    <td> <a href="{% url 'main:tbclist' %}">view</a> </td>
                </tr>
                <tr>
                    <td>TBB</td>
                    <td>1</td>
                    <td> <a href="{% url 'main:tbblist' %}">view</a> </td>
                </tr>
                <tr>
                    <td>Engineer Inspection</td>
                    <td>1</td>
                    <td> <a href="{% url 'main:inspection_list' %} ">view</a> </td>
                </tr>
                <tr>
                    <td>Pending For payment</td>
                    <td>1</td>
                    <td> <a href="{% url 'main:pfplist' %}">view</a> </td>
                </tr>
                <tr>
                    <td>TBD</td>
                    <td>1</td>
                    <td> <a href="{% url 'main:tbdlist' %}">view</a> </td>
                </tr>
            </tbody>
        </table>
<!-- Allocate ends here  -->

<!-- PFO starts here -->

<h3>PFO</h3>
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th>Case</th>
                    <th> Pending Cases</th>
                    <th> Operation</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Pending For Outbound-IW</td>
                    <td>1</td>
                    <td> <a href="{% url 'main:inpfolist' %}">view</a> </td>
                </tr>
                <tr>
                    <td>Pending For Outbound-OOW</td>
                    <td>1</td>
                    <td> <a href="{% url 'main:pfolist' %}">view</a> </td>
                </tr>
            </tbody>
        </table>

<!-- PFO ends here -->

<!-- Pending Inventory starts here  -->
        <h3>PFI</h3>
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th>Case</th>
                    <th> Pending Cases</th>
                    <th> Operation</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Pending For Inbound</td>
                    <td>1</td>
                    <td> <a href="{% url 'main:pending_inbound' %}">view</a> </td>
                </tr>
                <tr>
                    <td>Pending For Inventory-IW</td>
                    <td>1</td>
                    <td> <a href="#">view</a> </td>
                </tr>
                <tr>
                    <td>Pending For Inventory-OOW</td>
                    <td>1</td>
                    <td> <a href="#">view</a> </td>
                </tr>
            </tbody>
        </table>
<!-- Pending Inventory ends here  -->


<!--  Track Inventory starts here  -->
        <h3>Track Inventory Value</h3>
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th> Case </th>
                    <th> Pending Cases</th>
                    <th> Operation</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Pending For Inventory-OOW</td>
                    <td>1</td>
                    <td> <a href="">view</a> </td>
                </tr>
            </tbody>
        </table>
<!--  Track Inventory ends here  -->

<!--  Consumption Parameter starts here  -->
        {% comment %} <h3>Consumption Parameter</h3>
        <table width="100%">
            <thead>
                <tr>
                    <th> Part Code </th>
                    <th> Description </th>
                    <th> W/H Stock Quantity </th>
                    <th> Available Quantity </th>
                    <th> Sold Quantity </th>
                    <th> Sold Value </th>
                    <th> Operation</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td> CD20105858 </td>
                    <td>
                        Cp Plus Camera CP-VAC-D10L2-V2 HD Color Image Sensor
                        DOME 1 MP Camera IR Range of 20 Mtr.  720P-Resolution
                     </td>
                    <td> 50 </td>
                    <td> 10 </td>
                    <td> 5 </td>
                    <td> &#8377; 3875.00 </td>
                    <td> <a href="">view</a> </td>
                </tr>
                <tr>
                    <td> CD20105859 </td>
                    <td>
                        Cp Plus Camera CP-VAC-D10L2-V2 HD Color Image Sensor
                        DOME 1 MP Camera IR Range of 20 Mtr.  720P-Resolution
                     </td>
                    <td> 50 </td>
                    <td> 10 </td>
                    <td> 5 </td>
                    <td> &#8377; 3875.00 </td>
                    <td> <a href="">view</a> </td>
                </tr>
                <tr>
                    <td> CD20105860 </td>
                    <td>
                        Cp Plus Camera CP-VAC-D10L2-V2 HD Color Image Sensor
                        DOME 1 MP Camera IR Range of 20 Mtr.  720P-Resolution
                     </td>
                    <td> 50 </td>
                    <td> 10 </td>
                    <td> 5 </td>
                    <td> &#8377; 3875.00 </td>
                    <td> <a href="">view</a> </td>
                </tr>
                <tr>
                    <td> CD20105861 </td>
                    <td>
                        Cp Plus Camera CP-VAC-D10L2-V2 HD Color Image Sensor
                        DOME 1 MP Camera IR Range of 20 Mtr.  720P-Resolution
                     </td>
                    <td> 50 </td>
                    <td> 10 </td>
                    <td> 5 </td>
                    <td> &#8377; 3875.00 </td>
                    <td> <a href="">view</a> </td>
                </tr>
            </tbody>
        </table> {% endcomment %}
<!--  Consumption Parameter ends here  -->
{% endblock content %}

templates/login.html
{% load static %}
<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/login.css' %}">

    <title>User Login</title>
  </head>
  <body>
  

  
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img src="{% static 'image/undraw_remotely_2j6y.svg' %}" alt="Image" class="img-fluid">
        </div>
        <div class="col-md-6 contents">
          <div class="row justify-content-center">
            <div class="col-md-8">
              <div class="mb-4">
              <h3>Sign In</h3>
              <p class="mb-4">TO AOME CCTVSERV</p>
            </div>
            <form action="" method="POST">
              {% csrf_token %}
              <div class="form-group first">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username">

              </div>
              <div class="form-group last mb-4">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password">
                
              </div>
              
              <div class="d-flex mb-5 align-items-center">
                <label class="control control--checkbox mb-0"><span class="caption">Remember me</span>
                  <input type="checkbox"/>
                  <div class="control__indicator"></div>
                </label>
                <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span> 
              </div>

              <input type="submit" value="Log In" name="login" class="btn btn-block btn-primary">

              {% comment %} <span class="d-block text-left my-4 text-muted">&mdash; or login with &mdash;</span>
              
              <div class="social-login">
                <a href="" class="facebook">
                  <span class="icon-facebook mr-3"></span> 
                </a>
                <a href="" class="twitter">
                  <span class="icon-twitter mr-3"></span> 
                </a>
                <a href="" class="google">
                  <span class="icon-google mr-3"></span> 
                </a>
              </div> {% endcomment %}
            </form>
            </div>
          </div>
          
        </div>
        
      </div>
    </div>
  </div>

  
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/login.js' %}"></script>
  </body>
</html>