CRM/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/',include("main.urls",namespace="main")),
]

main/urls.py
from django.urls import path
from main import views
app_name = "main"

urlpatterns = [
    path("userlogin/",views.userlogin,name="userlogin"),
    path("userlogout/",views.userlogout,name="userlogout"),
    path("index/",views.index,name="index"),
    path('newservice/',views.newservice,name="newservice"),
    path('tbclist/',views.tbclist,name='tbclist'),
    path('tbblist/',views.tbblist,name='tbblist'),
    path('pfolist/',views.pfolist,name='pfolist'),
    path('inpfolist/',views.inpfolist,name='inpfolist'),
    path('pfplist/',views.pfplist,name='pfplist'),
    path('tbdlist/',views.tbdlist,name='tbdlist'),
    path('closedloglist/',views.closedloglist,name='closedloglist'),
    path('tbc/<str:sid>/',views.tbc,name='tbc'),
    path('tbb/<str:sid>/',views.tbb,name='tbb'),
    path('engineerinspection/<str:sid>/',views.engineerinspection,name='engineerinspection'),
    path('pendingforpayment/<str:osid>/',views.pendingforpayment,name='pendingforpayment'),
    path('pendingforoutbound/<str:isid>/',views.pendingforoutbound,name='pendingforoutbound'),
    path('inwarrantypendingforoutbound/<str:osid>/',views.inwarrantypendingforoutbound,name='inwarrantypendingforoutbound'),
    path('tbd/<str:logid>/',views.tbd,name='tbd'),
    path('productslist/',views.productlist,name='productlist'),
    path('iproduct/<str:partcode>/',views.getInventoryProduct,name='iproduct'),

    path('inventory/',views.inventory,name="inventory"),

    path('inpspectionlist/',views.inspection_list,name='inspection_list'),

    path('pending-inbound/',views.stockapproval,name="pending_inbound"),
    path('testing/',views.testingapi),

    path('test/',views.testing),

    path('logapi/',views.logapi),
    path('approval/',views.approvalapi),
]

main/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from main.models import Customer

class NewServiceForm(forms.ModelForm):
    complain = forms.CharField()
    remark = forms.CharField(widget=forms.Textarea(attrs={'cols': 33, 'rows': 5}))
    class Meta:
        model = Customer
        fields = "__all__"
        exclude = ['customer_id',]

        widgets = {
            'address': forms.Textarea(attrs={'cols': 33, 'rows': 5}),
        }

        labels = {
            'name':_("Full name"),
        }
        error_messages = {

            'name':{
                'required':_("Enter name"),
            }
        }
    
    

main/views.py
import json
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import render,redirect
from django.http import JsonResponse ,HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login ,logout
from rest_framework.parsers import JSONParser


from .mainapi import Log
from main.forms import NewServiceForm

from .models import (Customer, Engineer, EngineerBag, Inventory, Product, Service,
ComingStockLog,PendingForOutbound,StockPayment,OutboundStockHandler,StockPaymentHandler,ClosedLog,OutboundStock)
from .serializers import ComingStockSerializer,ComingStockLogSerializer


def userlogin(request):
    if request.method == "POST" and "login" in request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('/main/index/')
        else:
            return render(request,"login.html")
    return render(request,"login.html")

def userlogout(request):
    logout(request)
    return redirect('/main/userlogin/')

@login_required(login_url='/main/userlogin/')
def index(request):
    return render (request,"index.html")

@login_required(login_url='/main/userlogin/')
def tbclist(request):
    servicelist = Service.objects.all().filter(status="TBC")
    return render(request,'main/tbclist.html',{'services':servicelist})

@login_required(login_url='/main/userlogin/')
def tbblist(request):
    servicelist = Service.objects.all().filter(status="TBB")
    return render(request,'main/tbblist.html',{'services':servicelist})

@login_required(login_url='/main/userlogin/')
@csrf_exempt
def tbb(request,sid):

    engineerlist =  Engineer.objects.all()
    serviceRef = Service.objects.get(sid=sid)

    if request.method == "POST":
        try:
            post_data = json.loads(request.body.decode("utf-8"))
            data = post_data[:len(post_data)-1]
            info_data = post_data[-1]
            engineerRef = Engineer.objects.get(engineer_id = str(info_data['selected_engineer']))
            engineerRef.is_available = False
            engineerRef.serviceRef = serviceRef
            serviceRef.status = "EI"
            engineer_bag_setter(data,engineerRef)
            engineerRef.save()
            serviceRef.save()

            return HttpResponse(json.dumps({"response":"This is the response"}),content_type = 'application/json')
        except:
            HttpResponse(json.dumps({"Error":"There was an error"}),content_type = 'application/json')
        

    context = {
        'service':serviceRef,
        'engineerlist':engineerlist,

    }
    return render(request,'main/tbb.html',context)


def engineer_bag_setter(data,engineerRef,serviceRef=None):
    totalVal = 0
    if serviceRef == None:
        for product in data:
            partcodeRef = Product.objects.get(partcode = product['partcode'])
            productInInventory = Inventory.objects.get(productRef = partcodeRef)
            productInInventory.quantity -= int(product['quantity'])
            productInInventory.save()
            EngineerBag.objects.create(
                engineer_id = engineerRef,
                partcode = partcodeRef,
                serviceRef = engineerRef.serviceRef,
                price = product['price'],
                quantity = product['quantity']
            )
            totalVal += (int(product['price'])*int(product['quantity']))
    else:
        for product in data:
            partcodeRef = Product.objects.get(partcode = product['partcode'])
            productInInventory = Inventory.objects.get(productRef = partcodeRef)
            productInInventory.quantity -= int(product['quantity'])
            productInInventory.save()
            EngineerBag.objects.create(
                engineer_id = engineerRef,
                partcode = partcodeRef,
                serviceRef = serviceRef,
                price = product['price'],
                quantity = product['quantity']
            )

            totalVal += (int(product['price'])*int(product['quantity']))

    engineerRef.current_bag_value = totalVal
    engineerRef.save()
    return 201


@login_required(login_url='/main/userlogin/')
def tbc(request,sid):
    service = Service.objects.get(sid=sid)
    if request.method=="POST" and "accept" in request.POST:
        special_remark = request.POST['specialremark']
        service.special_remark = special_remark
        service.is_determined = True
        service.status = "TBB"
        service.save()
        messages.success(request,"Service Accepted !")

    return render(request,'main/tbc.html',{'service':service})

def latestuserid():
    user = Customer.objects.all().latest('customer_id')
    return user

def getuserid(userid):
    user = Customer.objects.get(customer_id = userid)
    return user

@login_required(login_url='/main/userlogin/')
def newservice(request):
    form = NewServiceForm()
    if request.method == "POST":
        form = NewServiceForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            contact_number = form.cleaned_data['contact_number']
            alternate_number = form.cleaned_data['alternate_number']
            gender = form.cleaned_data['gender']
            appelation = form.cleaned_data['appelation']
            email_id = form.cleaned_data['email_id']
            address = form.cleaned_data['address']
            city = form.cleaned_data['city']
            State = form.cleaned_data['State']
            pincode = form.cleaned_data['pincode']
            remark = form.cleaned_data['remark']
            complain = form.cleaned_data['complain']
            # print(name,contact_number,alternate_number,gender,appelation,email_id,address,city,State,pincode,remark,complain)
            Customer.objects.create(
                name = name,
                contact_number = contact_number,
                alternate_number = alternate_number,
                gender = gender,
                appelation = appelation,
                email_id = email_id,
                address = address,
                city = city,
                State = State,
                pincode = pincode,
            )
            creteduser = latestuserid()
            print(creteduser)
            user = getuserid(creteduser)
            print(user)
            Service.objects.create(
                customer_id = user,
                complain = complain,
                remark = remark,
            )
            messages.success(request,"Service Created Successfully!")
    else:
        form = NewServiceForm()
        
    context = {
        "form" : form,
    }
    return render(request,"main/newservice.html",context)

@login_required(login_url='/main/userlogin/')
def inspection_list(request):
    in_list = Service.objects.filter(status = "EI")
    context = {
        "in_list":in_list
    }
    return render(request,"main/inspectionlist.html",context)

@login_required(login_url='/main/userlogin/')
@csrf_exempt
def engineerinspection(request,sid):
    serviceObj = Service.objects.get(sid = sid)
    if serviceObj.status == "EI":
        engineers_assigned = Engineer.objects.filter(serviceRef = serviceObj)
        engineerlist =  Engineer.objects.all()
        inwarranty_used_stock = EngineerBag.objects.filter(serviceRef=serviceObj).filter(is_used=True).filter(is_inwarranty = True)
        outwarranty_used_stock = EngineerBag.objects.filter(serviceRef=serviceObj).filter(is_used=True).filter(is_inwarranty = False)
        products = EngineerBag.objects.filter(serviceRef=serviceObj).filter(is_used=False)
        
        if request.method == "POST" and "determine" in request.POST:
            try:
                post_data = json.loads(request.body.decode("utf-8"))
                print(post_data)

                data = post_data[:len(post_data)-1]
                info_data = post_data[-1]
                print(info_data)

                engineerRef = Engineer.objects.get(engineer_id = str(info_data['selected_engineer']))
                engineerRef.is_available = False
                engineerRef.serviceRef = serviceObj
                print(engineerRef,serviceObj)
                engineer_bag_setter(data,engineerRef,serviceObj)
                engineerRef.save()
                messages.success(request,"Engineer Assigned !")
                return HttpResponse(json.dumps({"response":"This is the response"}),content_type = 'application/json')
            except:
                messages.error(request,"Cant Assign Engineer !")
                return HttpResponse(json.dumps({"response":"Error"}),content_type = 'application/json')

        if request.method == "POST" and "rollback" in request.POST:
            if serviceObj.can_rollback == True:
                if products.count()>0:
                    for product in products:
                        inventoryProduct = Inventory.objects.get(productRef = product.partcode)
                        inventoryProduct.quantity += product.quantity
                        inventoryProduct.save()
                        products.delete()
                        messages.success(request,"Products rolledback to inventory successfully !")
            else:
                messages.warning(request,"Cannot Rollback until outbound is clear !")

        if request.method == "POST" and "inwarranty_outbound" in request.POST:
            if inwarranty_used_stock.count()>0:
                objectlist = []
                number_of_products = 0
                for product in inwarranty_used_stock:
                    obj = PendingForOutbound(
                        productRef = product.partcode,
                        quantity = product.quantity,
                        serviceRef = product.serviceRef,

main/templates/main/engineerinspection.html
{% extends 'base.html' %}
{% load static %}

{% block csslinks %}
    <link rel="stylesheet" href="{% static 'css/engineerinspection.css' %}">
{% endblock csslinks %}
{% block content %}


<div class="screen-box2"><div class="loader"></div></div>

<!-- POPUP WINDOW TO ADD SEARCH FOR PRODUCT FORM SERVER -->
<div class="screen-box">
    <div class="center-container">
        <div class="content">
            <div class="form-area">
                <div class="flex">

                    <div class="wrapper">
                        <input type="text" id="searchinput" autocomplete="off" placeholder="partcode/model number/description">

                        <!-- FILTERED PRODUCT LIST BOX  -->
                        <div class="autocomplete-box"></div>
                    </div> 

                    <!-- POPUP WINDOW BUTTON AREA -->            
                    <div class="button-area">
                        <button id="popWindowSelectBtn" class="simple-btn">select</button>
                        <button id="popWindowCancelBtn" class="simple-btn">cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- INFORMATION SECTION -->
<div class="container">
    <table class="detail-table">
        <tr>
            <th>service ID</th>
            <td>{{service.sid}}</td>

            <th>status</th>
            <td>{{service.status}}</td>

            <th>Creation Date/Time</th>
            <td>{{service.timestamp}}</td>

            <th>Engineers</th>
            
            <td>
                {% for engineer in engineers_assigned %}
                    <span>{{engineer.engineer_id}} | {{engineer.name}}</span>
                    <br>
                {% endfor %}
            </td>
            
        </tr>
        <tr>
            <th>dummy</th>
            <td>dummy</td>

            <th>dummy</th>
            <td>dummy</td>

            <th>dummy</th>
            <td>dummy</td>

            <th>dummy</th>
            <td>dummy</td>
        </tr>
    </table>
</div>
<br><br>

<form id="productForm" action="" method="POST">
    {% comment %} {% csrf_token %} {% endcomment %}
    <div class="container">
        <div class="assignbox">
            <table class="assigntable">
                <caption>Assign Another Engineer</caption>
                <!-- SELECT Engineer FIELD -->
                <tr>
                    <th><label for="engineer">Engineer*</label></th>
                    <td> 
                        <select name="engineer" id="engineer">
                            {% for eng in engineerlist %}
                                {% if eng.is_available == True %}
                                    <option value="{{eng.engineer_id}}">{{eng.name}} | Avaiable </option>
                                {% endif %}
                                {% if eng.is_available == False %}
                                    <option value="{{eng.engineer_id}}" disabled>{{eng.name}} | Working </option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </td>
                </tr>

                <!-- FORM FIELDS -->
                <tr>
                    <th>Product List</th>
                    <td>
                        <label for="partcode" >partcode/SN</label>
                            <input type="text" name="partcode" id="partcode" autocomplete="off">
                        <label for="decription">description</label>
                            <input type="text" name="description" id="description" style="width:400px;" readonly>
                        <label for="availableQuantity">Available Quantity</label>
                        <input type="number" id="availablequantity" name="availablequantity" style="width:100px;">
                        <label for="quantity">Quantity</label>
                        <input type="number" id="quantity" name="quantity" style="width:100px;">
                        <button type="submit" id="formAddBtn" name="formAddBtn" class="simple-btn">Add</button>
                    </td>
                </tr>

                <!-- DISPLAY LIST TABLE -->
                <tr>
                <th></th>
                <td>
                    <div class="container" style="overflow-y:auto; max-height:300px;max-width:1500px;" >
                        <table width="100%" class='list_table'>
                            <thead>
                                <tr>
                                    <th> PN </th>
                                    <th> serial number</th>
                                    <th> model number</th>
                                    <th>description</th>
                                    <th>price</th>
                                    <th>quantity</th>
                                    <th>total</th>
                                    <th>operation</th>
                                </tr>
                            </thead>
                            <tbody id="EngineerBagList"></tbody>
                        </table>
                    </div>
                </td>
                </tr>
                
                <!-- Remark -->
                <tr>
                    <th>Remark*</th>
                    <td>
                        <textarea name="remark" id="remark" cols="30" rows="5"></textarea>
                    </td>
                </tr>
            </table>
            <button type="submit" name="determine" id="determineBtn" class="btn">determine</button>
        </div>
    </div>


<div class="container">
    <h3>Engieer Bag</h3>
    <table width="100%" class='list_table'>
        <thead>
            <tr>
                <th> PN </th>
                <th> serial number</th>
                <th> model number</th>
                <th>description</th>
                <th>price</th>
                <th>quantity</th>
                <th>total</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                        <tr>
                            <td style="width:90px" >{{product.partcode.partcode}}</td>
                            <td style="width:90px" >{{product.partcode.serialnumber}}</td>
                            <td style="width:90px" >{{product.partcode.modelnumber}}</td>
                            <td style="width:600px" >{{product.partcode.description}}</td>
                            <td style="width:70px" >{{product.price}}</td>
                            <td style="width:70px" >{{product.quantity}}</td>
                            <td style="width:70px">{% widthratio product.price 1 product.quantity%}</td>
                        </tr>
            {% endfor %}
        </tbody>
    </table>
    <button type="submit" name="rollback" id="rollback" class="btn" style="position:absolute;right:10px;margin:5px;">rollback</button>
</div>

<div class="container">
    <h3>IN WARRANTY STOCK</h3>
    <table width="100%" class='list_table'>
        <thead>
            <tr>
                <th> PN </th>
                <th> serial number</th>
                <th> model number</th>
                <th>description</th>
                <th>price</th>
                <th>quantity</th>
                <th>total</th>
            </tr>
        </thead>
        <tbody>
            {% for product in inwarranty_used_stock %}
                        <tr>
                            <td style="width:90px" >{{product.partcode.partcode}}</td>
                            <td style="width:90px" >{{product.partcode.serialnumber}}</td>
                            <td style="width:90px" >{{product.partcode.modelnumber}}</td>
                            <td style="width:600px" >{{product.partcode.description}}</td>
                            <td style="width:70px" >{{product.price}}</td>
                            <td style="width:70px" >{{product.quantity}}</td>
                            <td style="width:70px">{% widthratio product.price 1 product.quantity%}</td>
                        </tr>
            {% endfor %}
        </tbody>
    </table>
    <button type="submit" name="inwarranty_outbound" id="inwarranty_rollbackBtn" class="btn" style="position:absolute;right:10px;margin:5px;">apply</button>
</div>


<div class="container">
    <h3>OUT WARRANTY STOCK</h3>
    <table width="100%" class='list_table'>
        <thead>
            <tr>
                <th> PN </th>
                <th> serial number</th>
                <th> model number</th>
                <th>description</th>
                <th>price</th>
                <th>quantity</th>
                <th>total</th>
            </tr>
        </thead>
        <tbody>
            {% for product in outwarranty_used_stock %}
                        <tr>
                            <td style="width:90px" >{{product.partcode.partcode}}</td>
                            <td style="width:90px" >{{product.partcode.serialnumber}}</td>
                            <td style="width:90px" >{{product.partcode.modelnumber}}</td>
                            <td style="width:600px" >{{product.partcode.description}}</td>
                            <td style="width:70px" >{{product.price}}</td>
                            <td style="width:70px" >{{product.quantity}}</td>
                            <td style="width:70px">{% widthratio product.price 1 product.quantity%}</td>
                        </tr>
            {% endfor %}
        </tbody>
    </table>
    <button type="submit" name="outwarranty_outbound" id="outwarranty_rollbackBtn" class="btn" style="position:absolute;right:10px;margin:5px;">apply</button>
</div>
<button type="submit" name="proceed" id="proceedBtn">Proceed</button>
</form>

{% for message in messages %}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    let msg = "{{message}}";
    msgTag = "{{message.tags}}";
    swal(msgTag.toUpperCase(),msg,msgTag);
</script>
{% endfor %}


{% endblock content %}

{% block jslinks %}
<script defer src=" {% static 'js/engineerinspection.js' %} "></script>
{% endblock jslinks %}

main/templates/main/inspectionlist.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th>agency ID</th>
                    <th> date/time</th>
                    <th> service ID</th>
                    <th>Type</th>
                    <th>cusomter name</th>
                    <th>contact number</th>
                    <th>compain</th>
                    <th>operation</th>
                </tr>
            </thead>
            <tbody>
                {% for inspec in in_list %}
                <tr>
                    <td>USER0001</td>
                    <td>{{inspec.timestamp}}</td>
                    <td>{{inspec.sid}}</td>
                    <td>{{inspec.service_type}}</td>
                    <td>{{inspec.customer_id.name}}</td>
                    <td>{{inspec.customer_id.contact_number}}</td>
                    <td>{{inspec.complain}}</td>
                    <td> <a href="{% url 'main:engineerinspection' sid=inspec.sid%}">dealwith</a> </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

main/templates/main/inventory.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th> Partcode </th>
                    <th> Description </th>
                    <th> Category </th>
                    <th> Quantity </th>
                    <th> Price </th>
                    <th> CGST </th>
                    <th> IGST </th>
                    <th> MSRP </th>
                    <th> Total </th>
                    <th> Operation </th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{product.productRef.partcode}}</td>
                    <td style="width:500px" >{{ product.productRef.description }}</td>
                    <td> -- </td>
                    <td>{{ product.quantity }}</td>
                    <td>₹ {{ product.price }}</td>
                    <td> {{product.cgst}}% </td>
                    <td> {{product.igst}}% </td>
                    <td>₹ {{product.msrp}}</td>
                    <td>₹ {{product.amount}}</td>
                    <td> <a href=""> view </a> </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

main/templates/main/pfolist.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th> agency ID </th>
                    <th> date/time </th>
                    <th> service ID </th>
                    <th> Type </th>
                    <th> cusomter name </th>
                    <th> contact number </th>
                    <th> compain </th>
                    <th> operation </th>
                </tr>
            </thead>
            <tbody>
                {% for pfo in pfo_list %}
                <tr>
                    <td>{{pfo.isid}}</td>
                    <td>{{pfo.timestamp}}</td>
                    <td>{{pfo.serviceRef}}</td>
                    <td>{{pfo.serviceRef.service_type}}</td>
                    <td>{{pfo.serviceRef.customer_id.name}}</td>
                    <td>{{pfo.serviceRef.customer_id.contact_number}}</td>
                    <td>{{pfo.serviceRef.complain}}</td>
                    <td> <a href="{% url 'main:pendingforoutbound' isid=pfo.isid%}">dealwith</a> </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

main/templates/main/stockapproval.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th> agency ID </th>
                    <th> date/time </th>
                    <th> service ID </th>
                    <th> Type </th>
                    <th> cusomter name </th>
                    <th> contact number </th>
                    <th> compain </th>
                    <th> operation </th>
                </tr>
            </thead>
            <tbody>
                {% for inspec in in_list %}
                <tr>
                    <td>USER0001</td>
                    <td>{{inspec.timestamp}}</td>
                    <td>{{inspec.sid}}</td>
                    <td>{{inspec.service_type}}</td>
                    <td>{{inspec.customer_id.name}}</td>
                    <td>{{inspec.customer_id.contact_number}}</td>
                    <td>{{inspec.complain}}</td>
                    <td> <a href="{% url 'main:engineerinspection' sid=inspec.sid%}">dealwith</a> </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

main/templates/main/tbblist.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th>agency ID</th>
                    <th> date/time</th>
                    <th> service ID</th>
                    <th>Type</th>
                    <th>cusomter name</th>
                    <th>contact number</th>
                    <th>compain</th>
                    <th>operation</th>
                </tr>
            </thead>
            <tbody>
                {% for service in services %}
                <tr>
                    <td>USER0001</td>
                    <td>{{service.timestamp}}</td>
                    <td>{{service.sid}}</td>
                    <td>{{service.service_type}}</td>
                    <td>{{service.customer_id.name}}</td>
                    <td>{{service.customer_id.contact_number}}</td>
                    <td>{{service.complain}}</td>
                    <td> <a href="{% url 'main:tbb' sid=service.sid%}">dealwith</a> </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

main/templates/main/tbclist.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th>agency ID</th>
                    <th> date/time</th>
                    <th> service ID</th>
                    <th>Type</th>
                    <th>cusomter name</th>
                    <th>contact number</th>
                    <th>compain</th>
                    <th>operation</th>
                </tr>
            </thead>
            <tbody>
                {% for service in services %}
                <tr>
                    <td>USER0001</td>
                    <td>{{service.timestamp}}</td>
                    <td>{{service.sid}}</td>
                    <td>{{service.service_type}}</td>
                    <td>{{service.customer_id.name}}</td>
                    <td>{{service.customer_id.contact_number}}</td>
                    <td>{{service.complain}}</td>
                    <td> <a href=" {% url 'main:tbc' sid=service.sid %} ">dealwith</a> </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

main/templates/main/tbdlist.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <table width="100%" class='list_table'>
            <thead>
                <tr>
                    <th>Log ID</th>
                    <th>date/time</th>
                    <th>service ID</th>
                    <th>Customer Name</th>
                    <th>Cusomter Phone</th>
                    <th>Complain</th>
                    <th>operation</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs %}
                <tr>
                    <td>{{log.logId}}</td>
                    <td>{{log.timestamp}}</td>
                    <td>{{log.serviceRef}}</td>
                    <td>{{log.cutomerId.name}}</td>
                    <td>{{log.cutomerId.contact_number}}</td>
                    <td>{{log.serviceRef.complain}}</td>
                    <td> <a href=" {% url 'main:tbd' logid=log.logId %} ">dealwith</a> </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}